site:
  title: "My Hirundo Site"
  url: "https://example.com"
  description: "A site built with Hirundo"
  language: "en-US"
  author:
    name: "Your Name"
    email: "your.email@example.com"

build:
  contentDirectory: "content"
  outputDirectory: "_site"
  staticDirectory: "static"
  templatesDirectory: "templates"

server:
  port: 8080
  liveReload: true
  cors:
    enabled: true
    allowedOrigins: ["http://localhost:*", "https://localhost:*"]
    allowedMethods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
    allowedHeaders: ["Content-Type", "Authorization"]
    maxAge: 3600
    allowCredentials: false

