name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: macos-14
    strategy:
      fail-fast: false
      matrix:
        xcode: ["16.1", "16.2"] # Approx: Swift 6.x
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode ${{ matrix.xcode }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}

      - name: Show Swift version
        run: swift --version

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            .build
          key: ${{ runner.os }}-spm-${{ matrix.xcode }}-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-${{ matrix.xcode }}-

      - name: Build
        run: swift build -v

      - name: Test
        run: swift test -v


  tsan:
    name: ThreadSanitizer
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode 16.1
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "16.1"

      - name: Show Swift version
        run: swift --version

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            .build
          key: ${{ runner.os }}-spm-tsan-16.1-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-tsan-16.1-

      - name: Build (Debug)
        run: swift build -c debug -v

      - name: Test with ThreadSanitizer
        run: swift test -c debug --sanitize=thread -v
